STARFLEET:
  DeploymentRegion: us-east-1  # Replace me
  TemplateBucket: REPLACE-ME
  FanOutQueueUrl: https://some.url.amazonaws.com/replace-me
  AccountIndex: StarfleetDefaultAccountIndex
  LogLevel: DEBUG
  ThirdPartyLoggerLevels:
    botocore: CRITICAL
    'urllib3.connectionpool': CRITICAL


AccountIndexGeneratorShip:
  Enabled: True
  TemplatePrefix: AccountIndexGenerator/REPLACE-ME.YAML
  InvocationQueueUrl: https://replace.me.sqs.amazonaws.com/REPLACE-ME
  InvocationSources:
    - EVENTBRIDGE_TIMED_EVENT
  EventBridgeTimedFrequency: HOURLY
  OrgAccountAssumeRole: starfleet-worker-role
  OrgAccountId: "REPLACEME"
  OrgRootId: "r-eplaceme"
  DescribeRegionsAssumeRole: starfleet-worker-role


StarfleetDefaultAccountIndex:
  IndexBucket: REPLACE-ME
  BucketRegion: REPLACE-ME
  IndexObjectPath: REPLACE-ME
