# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      boto-dependencies:
        # A pattern can be...
        patterns:
          - "boto*"
      linters:
        patterns:
          - "black"
          - "pylint"
          - "flake8"
      primary-dev-dependencies:
        patterns:
          - "tox"
          - "mkdocs*"
          - "pytest*"
