site_name: ✨Starfleet✨
# Replace this once launched somewhere...
site_url: https://github.com/gemini-oss/starfleet
repo_url: https://github.com/gemini-oss/starfleet
docs_dir: mkdocs
copyright: Copyright &copy; 2023 - Gemini
theme:
  name: material
  font:
    text: Inter
  logo: logo_files/Logo.png
  favicon: logo_files/chmmr.png
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.sections
    - navigation.footer
    - navigation.tabs

plugins:
  - search
  - gen-files:
      scripts:
        - mkdocs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 3
      permalink: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Architecture:
    - Architecture Overview: architecture/Overview.md
    - Worker Ships: architecture/WorkerShips.md
    - Configuration: architecture/Configuration.md
    - Payload Templates: architecture/PayloadTemplates.md
    - Account Index: architecture/AccountIndex.md
    - Resident IAM Role: architecture/ResidentIAMRole.md
    - Starbase: architecture/Starbase.md
    - CLI: architecture/CLI.md
  - Installation Guide:
    - Installation Overview: installation/Overview.md
    - Set up IAM: installation/IAM.md
    - Prepare Configuration: installation/PrepareConfiguration.md
    - Prepare Payload Templates: installation/PreparePayload.md
    - Run AWS SAM: installation/RunSAM.md
    - Make the Account Index: installation/MakeAccountIndex.md
    - Wrapping Up: installation/WrapUp.md
  - User Guide:
    - Overview: userGuide/Overview.md
    - Starbase: userGuide/Starbase.md
    - Account Index Generator: userGuide/AccountIndexGenerator.md
    - AWS Config Worker:
      - Overview: userGuide/awsConfig/AWSConfigWorker.md
      - Installation: userGuide/awsConfig/Installation.md
      - Template: userGuide/awsConfig/Template.md
  - Developer Guide:
    - Developer Overview: developerGuide/Overview.md
    - Primary Components:
      - Loggers: developerGuide/primaryComponents/Loggers.md
      - Configuration Manager: developerGuide/primaryComponents/ConfigurationManager.md
      - Worker Ships:
        - Overview - Ship Schematics: developerGuide/primaryComponents/workerShips/Overview.md
        - Lambda Entrypoints: developerGuide/primaryComponents/workerShips/LambdaEntrypoints.md
        - CLI: developerGuide/primaryComponents/workerShips/CLI.md
        - Worker Ship Loader: developerGuide/primaryComponents/workerShips/Loader.md
      - Account Indexer: developerGuide/primaryComponents/AccountIndexer.md
    - AWS SAM Configuration: developerGuide/SAMConfiguration.md
    - Check List: developerGuide/CheckList.md
  - Code Reference: reference/
