[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "starfleet"
authors = [
    {name = "Gemini", email = "careers@gemini.com"},
    {name = "Mike Grima", email = "michael.grima@gemini.com"},
]
version = "0.0.1"
dynamic = ["dependencies"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file = ["src/requirements.txt"]}

[project.scripts]
starfleet = "starfleet.cli.entrypoint:cli"

[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "black",
    "flake8",
    "pylint",
    "tox",
    "moto",
    "mkdocs"
]

[tool.pytest.ini_options]
#pythonpath = [
#    ".",
#    "src"
#]
log_cli = true

[tool.black]
line-length = 160
